# https://pentacent.medium.com/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71
version: '3'

services:
  https-portal:
    image: steveltn/https-portal:latest
    volumes:
      - ./data/ssl_certs:/var/lib/https-portal
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: 'overfronted.net -> http://127.0.0.1:3000'
      # STAGE: production
      STAGE: staging
