name: CI

on:
  issues:
    types: [opened, edited]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Sync articles
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          whoami
          cd personal-bench-deploy
          ls -al
        
