name: CI

on:
  issues:
    types: [opened, edited]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Sync articles
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        scripts: |
          cd personal-bench-deploy/data
          git push
        
